package formTurnir;

import domain.Turnir;
import models.TableModelTurniri;

/**
 *Forma za pretragu turnira koji postoje u bazi.
 *
 * @author Kosta
 */
public class FormPretragaTurnira extends javax.swing.JDialog {
	/**
     * Konstruktor koji sluzi za kreiranje same forme. Postavlja lokaciju same forme
     * na ekranu, postavlja naslov i inicijalizuje njene osnovne komponente.
     * 
     * @param parent forma roditelj iz koje se postojeca otvara
     * @param modal predstavlja modalitet
     */
    public FormPretragaTurnira(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        TableModelTurniri model = new TableModelTurniri();
        Thread th = new Thread(model);
        th.start();
        tblTurniri.setModel(model);
        setTitle("Pretraga turnira");
    }

    /**
     * Metoda koja je napravljena od strane Form Editora sa osnovnim podesavanjima
     * i ne smije se mijenjati(inace je onemoguceno)
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTurniri = new javax.swing.JTable();
        txtPretraga = new javax.swing.JTextField();
        btnDetalji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Pretraga (naziv turnira):");

        tblTurniri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTurniri);

        txtPretraga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPretragaKeyReleased(evt);
            }
        });

        btnDetalji.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnDetalji.setText("Detalji turnira");
        btnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetaljiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPretraga))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(309, 309, 309)
                                .addComponent(btnDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDetalji)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        
    /**
     * Funkcionalnost koja prikazuje rezultate pretrage tek nakon sto je pusten
     * klik na tastaturi.
     * 
     * @param evt event listener
     */
    private void txtPretragaKeyReleased(java.awt.event.KeyEvent evt) {                                        
        String param = txtPretraga.getText();
        ((TableModelTurniri) tblTurniri.getModel()).setParametar(param);
    }                                       
    /**
     * Dugme koje na osnovu izabranog reda u tabeli pretrazenih turnira prikazuje dalje
     * detalje o tom turniru.
     * 
     * @param evt event listener
     */
    private void btnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {                                           
        
        int row = tblTurniri.getSelectedRow();
        
        if (row >= 0) {
            Turnir t = ((TableModelTurniri) tblTurniri.getModel()).getSelectedTurnir(row);
            new FormDetaljiTurnira(this, rootPaneCheckingEnabled, t).setVisible(true);
        }
        
    }                                          

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnDetalji;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTurniri;
    private javax.swing.JTextField txtPretraga;
    // End of variables declaration                   
    /**
     * Poziva tabelu turnire da se azuriraju automatski ukoliko je izvrseno
     * brisanje nekog turnira iz baze.
     */
    void refreshTable() {
        TableModelTurniri tm = (TableModelTurniri) tblTurniri.getModel();
        tm.refreshTable();
    }

}

